# Generated by Django 4.2.4 on 2023-09-04 11:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='core/assets/imgs/vendor/vendor-header-bg.png', upload_to=core.models.user_directory_path),
        ),
    ]
