# Generated by Django 4.2.4 on 2023-09-04 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufac_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=10, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Organic', max_length=100),
        ),
    ]
