# Generated by Django 4.2.4 on 2023-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_product_life_product_manufac_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
