# Generated by Django 4.2.4 on 2023-09-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_life_product_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='shipping_on_time',
            new_name='ship_on_time',
        ),
    ]
