# Generated by Django 4.2.4 on 2023-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tag_title_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
