# Generated by Django 4.2.4 on 2023-09-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_tag_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
