# Generated by Django 4.2.5 on 2023-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='ratings',
            field=models.IntegerField(choices=[(1, '❤️💔💔💔💔'), (2, '❤️❤️💔💔💔'), (3, '❤️❤️❤️💔💔'), (4, '❤️❤️❤️❤️💔'), (5, '❤️❤️❤️❤️❤️')], default=None),
        ),
    ]
