# Generated by Django 4.2.3 on 2023-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('index_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('level', models.IntegerField(choices=[(100, 100), ('200', 200), ('300', 300), ('400', 400)])),
            ],
        ),
    ]
