# Generated by Django 4.2.3 on 2023-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[(100, 100), ('200', 200), ('300', 300), ('400', 400)], max_length=3),
        ),
    ]
