# Generated by Django 4.2.3 on 2023-07-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_student_level_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
