# Generated by Django 4.2.3 on 2023-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(blank=True, max_length=6, null=True)),
                ('coursetitle', models.CharField(max_length=300, unique=True)),
                ('credithours', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
    ]
