# Generated by Django 4.2.3 on 2023-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credithours',
            field=models.CharField(default=3, max_length=2),
        ),
    ]
