# Generated by Django 4.2.3 on 2023-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_courses_credithours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credithours',
            field=models.CharField(choices=[(1, 1), (3, 3), (6, 6), (9, 9), (12, 12)], default=3, max_length=2),
        ),
    ]
