# Generated by Django 4.2.3 on 2023-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_courses_credithours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='coursecode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='coursetitle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexnumber', models.ManyToManyField(to='account.courses')),
            ],
        ),
    ]
