# Generated by Django 4.2.3 on 2023-07-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_courses_course_rename_results_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
