# Generated by Django 4.2.3 on 2023-08-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commet_count',
            new_name='comment_count',
        ),
    ]
