# Generated by Django 4.2.3 on 2023-08-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
