# Generated by Django 4.2.3 on 2023-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, default='Zoner Photo Studio X 19 Free Download Latest Version for Windows. The program and all files are checked and installed manually before uploading, program is working perfectly fine without any problem. It is full offline installer standalone setup of Zoner Photo Studio X 19 Free Download for supported version of Windows.', null=True),
        ),
    ]
