# Generated by Django 4.2.5 on 2023-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
