# Generated by Django 4.2.4 on 2023-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default="I'm moltivated Full stack developer", max_length=200),
        ),
    ]
