# Generated by Django 4.2.4 on 2023-08-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
