# Generated by Django 4.2.4 on 2023-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_categoory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
